### ISSUE TITLE
`Receipt` Should Read `Recipe` and `Ingridents` `Ingridients`

### ISSUE THREAD

**Issue by texnixe** [moritzz/Kirby-Recipe#1]
Hi Moritz, the title is a bit misleading, it should be called recipe. Maybe a receipt collection would also make sense (e.g. for tax purposes), but that's another story. There's also another typo: ingridents should be ingridients in the blueprints.

**Comment by moritzz** [comment]
Oops! I'll correct that with the next release. Thanks a lot for the hint, @texnixe and see you.

**Comment by moritzz** [comment]
Done! :)
